### ISSUE TITLE
Unable to connect to CompactLogix PLC

### ISSUE THREAD

**Issue by patrickjmcd** [cmseaton42/node-ethernet-ip#1]
When using the code in "Getting Connected", I'm getting an error while attempting to read PLC properties.

## My code 
```
const { Controller } = require("ethernet-ip");

const PLC = new Controller();

// Controller.connect(IP_ADDR[, SLOT])
// NOTE: SLOT = 0 (default) - 0 if CompactLogix
PLC.connect("192.168.1.11", 0).then(() => {
    console.log(PLC.properties);
}).catch(err => console.log(err));
```

## Error message
```
{ generalStatusCode: 8, extendedStatus: [] }
```

## Environment
```
node --version
v8.5.0
```

- PLC: CompactLogix 1769-L18ER-BB1B, V30.11

It looks like the issue is being caused by the readWallClock function not being supported by CompactLogix PLC's

**Comment by cmseaton42** [comment]
Working on the patch now! Preciate the help in tracking this down!
