### ISSUE TITLE
Keep values current even if value hasn't changed.

### ISSUE THREAD

**Issue by patrickjmcd** [cmseaton42/node-ethernet-ip#15]
Add a parameter to the Tag class to allow values to be updated even if the value has not changed.

## Current Behavior

Currently, if a tag value is initialized or changed, the Tag emits an Initialized or Changed event. If values are being graphed and the value has not changed, this could result in graphs looking really weird. It also could seem to the user that the data connection has been broken.

## Expected Behavior

In order to keep values current, implement a KeepAlive event to periodically (but infrequently) update the stored value of the tag based on a keepAlive property of the tag.

## Possible Solution (Optional)

Implement a KeepAlive event to periodically (but infrequently) update the stored value of the tag based on a keepAlive property of the tag.

## Context

Graphs that include values that don't change look weird.

**Comment by cmseaton42** [comment]
Addressed with #16
