### ISSUE TITLE
is it possible to convert this code to C#?

### ISSUE THREAD

**Issue by wyddd** [cmseaton42/node-ethernet-ip#22]
# General Question
Is it possible to convert this code to C#?

**Comment by cmseaton42** [comment]
Absolutely! 😄 

The implementation would be different though as javascript works in an asynchronous fashion by default thus the Socket IO was written in a way that takes advantage of what javascript does best. I imagine this would change in a C# implementation. That said, anything synchronous within the source (building message buffers, etc) could be easily adapted.  

Does this answer your question?

**Comment by jhenson29** [comment]
C# has asynchronous programming. I'm not familiar enough with aync in C# (or javascript in general) to compare/contrast them, but C# does have `await` and `async` keywords.

**Comment by cmseaton42** [comment]
@jhenson29 I did not know that (not a .net guy tbh). But if so then it may be easier to convert then I thought.  You would just need to find a good TCP/IP socket class to use as a base.

**Comment by patrickjmcd** [comment]
Thats the exact issue I'm having with Swift right now... finding the right Socket class to extend

**Comment by patrickjmcd** [comment]
But to help answer the question, yes, it should be possible, _but_ it's not in the scope of this project. If you'd like to start your own project and use this code as a reference, be sure to let us know and we'll follow along and help as we can.

**Comment by cmseaton42** [comment]
closing this
