### ISSUE TITLE
Wrong Error Message

### ISSUE THREAD

**Issue by hirokiht** [cmseaton42/node-ethernet-ip#27]
Should be "Path must be of type Buffer"
https://github.com/cmseaton42/node-ethernet-ip/blob/1529d4f869ee8f504b2bba445ab5b766ceba38e9/src/enip/cip/unconnected-send/index.js#L57

**Comment by cmseaton42** [comment]
Ill roll this clarification into the next patch release 👍 

Thanks for the heads up @hirokiht
